name: Debug Build Path

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Where is everything?
      run: |
        echo "Root directory contents:"
        ls -F
        echo "Looking for gradlew in all subdirectories:"
        find . -name "gradlew"
